language: ruby

before_install:
  - gem update --system 2.1.11
  - gem --version

rvm:
  - 1.8.7
  - 1.9.3

script: 'bundle exec rake rspec'

env:
  - PUPPET_VERSION="2.7"
  - PUPPET_VERSION="3.0"

branches:
  only:
    - master
    - develop
